### ISSUE TITLE
Precision?

### ISSUE THREAD

**Issue by chetmurthy** [graelo/si-scale#8]
I just found this package, and it's great!  I wonder, have you thought about adding support for precision?  That is to say, when you print seconds, the number that gets printed as `178.844052305 s` would, with three digits of precision after the decimal point, be printed as `178.844 s`.  And `83.99999999999999 ns` would come out as `84.000 ns`.

I'm in the middle of actually using your package, but when. I get done, I'll circle back and have a look, if you don't already have thoughts on how to do this.  But figured I ought to mention this, since it's sort of an obvious thing one might want.

**Comment by graelo** [comment]
Hi, thanks for the kind feedback, it's always super cool to hear.

I have not really encountered such a situation, but I totally agree it's an obvious thing one might want. I'm currently not working on the package, so please feel free to ping me again with ideas or code, as you see fit.

Cheers!

**Comment by graelo** [comment]
Hi, I've recently had time to make a pass on this crate, and I added a couple of unit tests to show your use case is handled:

https://github.com/graelo/si-scale/blob/a51b8d1e3ee2e55458ea884c7f4fd18bd98e17e1/src/helpers.rs#L368-L377

Does this correspond to your expectations?

**Comment by chetmurthy** [comment]
Ah, I wasn't suggesting that one would want a `seconds3` function, but more generally, that one would want to be able to specify precision.  But prompted by your comment, I went digging, and it appears that there's a way to do this already, albeit less dynamically than I would like:
```
scale_fn!(seconds3,
          base: B1000,
          constraint: UnitAndBelow,
          mantissa_fmt: "{:.3}",
          unit: "s",
          doc: "Print a value in seconds with 3 decimals.");
```
This is enough for almost all uses, since arguably hardly anybody wants to dynamically change precision.

Excellent!  Thank you!
